# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

groupCommand <- function(fragments, some_whitelist_cells = NULL, max_lines = 0L) {
    .Call('_Signac_groupCommand', PACKAGE = 'Signac', fragments, some_whitelist_cells, max_lines)
}

