# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

filterCells <- function(fragments, outfile, keep_cells, buffer_length, verbose = TRUE) {
    .Call('_Signac_filterCells', PACKAGE = 'Signac', fragments, outfile, keep_cells, buffer_length, verbose)
}

groupCommand <- function(fragments, some_whitelist_cells = NULL, max_lines = 0L, verbose = TRUE) {
    .Call('_Signac_groupCommand', PACKAGE = 'Signac', fragments, some_whitelist_cells, max_lines, verbose)
}

splitFragments <- function(fragments, cells, idents, unique_idents, outdir, suffix, buffer_length, append = FALSE, verbose = TRUE) {
    .Call('_Signac_splitFragments', PACKAGE = 'Signac', fragments, cells, idents, unique_idents, outdir, suffix, buffer_length, append, verbose)
}

validateCells <- function(fragments, cells, find_n, max_lines = 0L, verbose = TRUE) {
    .Call('_Signac_validateCells', PACKAGE = 'Signac', fragments, cells, find_n, max_lines, verbose)
}

